hello_world/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView
from aircraft import views
from hello_world.core import views as core_views
from aircraft.views import delete_note, edit_note, unit1_notes_table

urlpatterns = [
    # Redirect root URL to login
    path("", RedirectView.as_view(url='/login/', permanent=True), name='home'),
    path("index/", login_required(core_views.index), name='index'),
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('unit1table/', unit1_notes_table, name='unit1notes_table'),
    path('add-data-url/', views.add_data, name='add_data'),
    path('add-aircraft-note/', views.aircraft_note_create, name='add_aircraft_note'),
    path('aircraft-notes/', views.aircraft_note_list, name='aircraft_notes'),
    path('edit-note/<int:note_id>/', views.edit_note, name='edit_note'),
    path('delete-note/<int:note_id>/', delete_note, name='delete_note'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aircraft/models.py
from django.db import models
from django.utils import timezone

class AircraftNote(models.Model):
    STATUS_CHOICES = [
        ('incoming', 'Incoming'),
        ('departing', 'Departing'),
        ('quickturn', 'Quickturn'),
        ('off_ramp', 'Off-Ramp'),
        ('standby', 'Standby'),
        ('maintenance', 'Maintenance'),
        ('overnight', 'Overnight'),
    ]

    LOCATION_CHOICES = [
        ('hanger_1', 'H1'),
        ('hanger_2', 'H2'),
        ('hanger_3', 'H3'),
        ('hanger_4', 'H4'),
        ('row_1', 'R1'),
        ('row_2', 'R2'),
        ('row_3', 'R3'),
        ('row_4', 'R4'),
        ('row_5', 'R5'),
        ('row_6', 'R6'),        
        ('tie_down', 'T-D'),
        ('gama', 'Gama'),
        ('off_ramp', 'O-R'),
        ('customs', 'Cstm'),
        ('netjets', 'NJ'),
        
    ]

    FUEL_FORMAT_CHOICES = [
        ('lbs', 'lbs'),
        ('kgs', 'kgs'),
        ('gallons', 'gallons'),
    ]

    FUEL_TYPE_CHOICES = [
        ('jet_a_neg', 'Jet-'),
        ('jet_a_pos', 'Jet+'),
        ('avgas', 'Avgas'),
    ]

    LAV_STATUS_CHOICES = [
        ('none', 'None'),
        ('fwr', 'Fwr'),
        ('aft', 'Aft'),
        ('fwr_aft', 'Fwr & Aft'),
        ('completed', 'Completed'),
    ]

    LAV_TYPE_CHOICES = [
        ('full', 'Full'),
        ('dump', 'Dump'),
        ('rinse', 'Rinse'),
    ]

    WATER_SERVICE_STATUS_CHOICES = [
        ('none', 'None'),
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]

    GPU_STATUS_CHOICES = [
        ('none', 'None'),
        ('stage', 'Stage'),
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]

    Oil_STATUS_CHOICES = [
        ('none', 'None'),
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]

    CUSTOMER_TYPE_CHOICES = [
        ('none', 'None'),
        ('based_tenant', 'Based Tenant'),
        ('signature_silver', 'Signature Status Silver'),
        ('signature_gold', 'Signature Status Gold'),
        ('signature_platinum', 'Signature Status Platinum'),
    ]

    TRANSPORTATION_STATUS_CHOICES = [
        ('none', 'None'),
        ('personal', 'Personal'),
        ('driver', 'Driver'),
        ('rental', 'Rental'),
        ('self-park', 'Self-Park'),
        ('Ride Share', 'Ride Share'),
    ]
    
    CATERING_STATUS_CHOICES = [
        ('none', 'None'),
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]

    OIL_STATUS_CHOICES = [
        ('none', 'None'),
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]

    VACUUM_STATUS_CHOICES = [
        ('none', 'None'),
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]

    LADDER_STATUS_CHOICES = [
        ('none', 'None'),
        ('active', 'Active'),
        ('completed', 'Completed'),
    ]



    tail_number = models.CharField(max_length=10 ,null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES ,null=True, blank=True)
    service_time = models.DateTimeField(verbose_name='Service Time' ,null=True, blank=True)
    location = models.CharField(max_length=30, choices=LOCATION_CHOICES ,null=True, blank=True)
    aircraft_model = models.CharField(max_length=50 ,null=True, blank=True)
    eta = models.DateTimeField(verbose_name='Estimated Time of Arrival', null=True, blank=True)
    etd = models.DateTimeField(verbose_name='Estimated Time of Departure', null=True, blank=True)
    passenger_count = models.IntegerField(null=True, blank=True)
    fuel_qty = models.IntegerField(verbose_name='Fuel Quantity', null=True, blank=True)
    fuel_format = models.CharField(max_length=10, choices=FUEL_FORMAT_CHOICES, null=True, blank=True)
    fuel_type = models.CharField(max_length=10, choices=FUEL_TYPE_CHOICES, null=True, blank=True)
    lav_status = models.CharField(max_length=10, choices=LAV_STATUS_CHOICES, null=True, blank=True)
    lav_type = models.CharField(max_length=10, choices=LAV_TYPE_CHOICES, null=True, blank=True)
    lav_gallons = models.IntegerField(null=True, blank=True)
    water_service_status = models.CharField(max_length=10, choices=WATER_SERVICE_STATUS_CHOICES, null=True, blank=True)
    gpu_status = models.CharField(max_length=10, choices=GPU_STATUS_CHOICES, null=True, blank=True)
    transportation_status = models.CharField(max_length=10, choices=TRANSPORTATION_STATUS_CHOICES, null=True, blank=True)
    catering_status = models.CharField(max_length=10, choices=CATERING_STATUS_CHOICES, null=True, blank=True)
    catering_number = models.CharField(max_length=50, null=True, blank=True)
    pic = models.CharField(max_length=50, null=True, blank=True)  # PIC stands for Paper, Ice, Coffee
    customer_type = models.CharField(max_length=30, choices=CUSTOMER_TYPE_CHOICES, null=True, blank=True)
    oil_status = models.CharField(max_length=10, choices=OIL_STATUS_CHOICES, null=True, blank=True)
    oil_type = models.CharField(max_length=50, null=True, blank=True)
    oil_qty = models.IntegerField(null=True, blank=True)
    ladder_status = models.CharField(max_length=10, choices=LADDER_STATUS_CHOICES, null=True, blank=True)
    vacuum_status = models.CharField(max_length=10, choices=VACUUM_STATUS_CHOICES, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now ,null=True, blank=True)

hello_world/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from aircraft.models import AircraftNote
from aircraft import views

@login_required
def index(request):
    context = {
        "title": "Django example",
    }
    notes = AircraftNote.objects.all()
    return render(request, 'index.html', {'notes': notes})

   

hello_world/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="unit-one-ui">
    <div class="banner">
        <h1>Unit One UI</h1>
    </div>
    <h2>Unit One Notes:
        <button id="addNoteButton" class="btn btn-secondary">Add Aircraft Note</button>
    </h2>
    <div class="table-responsive">
        {% include 'unit1table.html' with notes=notes %}
    </div>
</div>

{% endblock %}

hello_world/templates/login.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <!-- Title at the top of the page -->
    <div class="row">
        <div class="col-12">
            <h2 class="text-center mt-4">Ramp Tech Assistant</h2>
        </div>
    </div>

    <!-- Centered login form -->
    <div class="row justify-content-center align-items-center" style="height: 70vh;">
        <div class="col-md-4">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-custom-dark btn-block">Login</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

hello_world/templates/unit1table.html
<!-- notes_table.html -->

<table id="notesTable" class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>created</th>
            <th>Tail</th>
            <th>Status</th>
            <th>Service Time</th>
            <th>A/C Model</th>
            <th>Loc.</th>
            <th>ETA</th>
            <th>ETD</th>
            <th>Pax</th>
            <th>Fuel Type</th>
            <th>Fuel QTY</th>
            <th>Fuel Format</th>
            <th>Lav Status</th>
            <th>Lav Type</th>
            <th>Lav Gal.</th>
            <th>Water Status</th>
            <th>GPU</th>
            <th>Transp.</th>
            <th>PIC</th>
            <th>Cat.</th>
            <th>Cat. #</th>
            <th>Vacuum</th>
            <th>Oil</th>
            <th>Oil Type</th>
            <th>Oil QTY</th>
            <th>Ladder</th>
            <th>Notes</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for note in notes %}
        <tr>
            <td>{{ note.created_at|date:"m/d H:i" }}</td>
            <td>{{ note.tail_number }}</td>
            <td>{{ note.get_status_display }}</td>
            <td>
                {% if note.status == 'incoming' or note.status == 'quickturn' %}
                    {{ note.eta|date:"m/d H:i" }}
                {% elif note.status == 'departing' %}
                    {{ note.etd|date:"m/d H:i" }}
                {% elif note.status == 'off_ramp' %}
                    {{ note.eta|date:"m/d H:i" }}
                {% elif note.status == 'standby' or note.status == 'maintenance' %}
                    {{ note.etd|date:"m/d H:i" }}
                {% elif note.status == 'overnight' %}
                    {{ note.etd|date:"m/d H:i" }}
                {% endif %}
            </td>
            <td>{{ note.aircraft_model }}</td>
            <td>{{ note.get_location_display }}</td>
            <td>{{ note.eta|date:"m/d H:i" }}</td>
            <td>{{ note.etd|date:"m/d H:i" }}</td>
            <td>{{ note.passenger_count }}</td>
            <td>{{ note.get_fuel_type_display }}</td>
            <td>{{ note.fuel_qty }}</td>
            <td>{{ note.fuel_format }}</td>
            <td>{{ note.lav_status }}</td>
            <td>{{ note.lav_type }}</td>
            <td>{{ note.lav_gallons }}</td>
            <td>{{ note.water_service_status }}</td>
            <td>{{ note.gpu_status }}</td>
            <td>{{ note.transportation_status }}</td>
            <td>{{ note.pic }}</td>
            <td>{{ note.catering_status }}</td>
            <td>{{ note.catering_number }}</td>
            <td>{{ note.vacuum_status }}</td>
            <td>{{ note.oil_status }}</td>
            <td>{{ note.oil_type }}</td>
            <td>{{ note.oil_qty }}</td>
            <td>{{ note.ladder_status }}</td>
            <td>{{ note.notes }}</td>
            <td><button class="btn btn-secondary edit-btn" data-note-id="{{ note.id }}" ... >Edit</button>
        </tr>
        {% endfor %}
    </tbody>
</table>

hello_world/templates/your_list_template.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Aircraft Notes</h2>
    <ul>
        {% for note in notes %}
            <li>{{ note.tail_number }} - {{ note.status }}</li>  <!-- Display fields as needed -->
        {% endfor %}
    </ul>
</div>
{% endblock %}

hello_world/templates/your_template.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Add Aircraft Note</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Submit</button>
        <button type="button" class="btn btn-secondary" onclick="goBack()">Cancel</button>
    </form>
</div>
<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock %}